insert into user (name, SUS_ID) values ("Carlos", 1);
insert into user (name, SUS_ID) values ("Matheus", 2);
insert into user (name, SUS_ID) values ("Vitor", 3);
insert into user (name, SUS_ID) values ("Brenda", 4);
insert into user (name, SUS_ID) values ("Camila", 5);
insert into user (name, SUS_ID) values ("Lucas", 6);
insert into user (name, SUS_ID) values	("Felipe", 	7	);
insert into user (name, SUS_ID) values	("Tainá", 	8	);
insert into user (name, SUS_ID) values	("Alexandre", 	9	);
insert into user (name, SUS_ID) values	("Fernanda", 	10	);
insert into user (name, SUS_ID) values	("Fernando", 	11	);
insert into user (name, SUS_ID) values	("João", 	12	);
insert into user (name, SUS_ID) values	("Joana", 	13	);
insert into user (name, SUS_ID) values	("Jonas", 	14	);
insert into user (name, SUS_ID) values	("José", 	15	);
insert into user (name, SUS_ID) values	("Judas", 	16	);
insert into user (name, SUS_ID) values	("Guilherme", 	17	);
insert into user (name, SUS_ID) values	("Garona", 	18	);
insert into user (name, SUS_ID) values	("Arly", 	19	);
insert into user (name, SUS_ID) values	("Luciene", 	20	);
insert into user (name, SUS_ID) values	("Daniel", 	21	);
insert into user (name, SUS_ID) values	("Daniela", 	22	);
insert into user (name, SUS_ID) values	("Katy", 	23	);
insert into user (name, SUS_ID) values	("Avicii", 	24	);
insert into user (name, SUS_ID) values	("Lara", 	25	);
insert into user (name, SUS_ID) values	("Amanda", 	26	);
insert into user (name, SUS_ID) values	("Lunarde", 	27	);
insert into user (name, SUS_ID) values	("Italo", 	28	);
insert into user (name, SUS_ID) values	("Josias", 	29	);
insert into user (name, SUS_ID) values	("Maria", 	30	);
insert into user (name, SUS_ID) values	("Macio", 	31	);
insert into user (name, SUS_ID) values	("Marco", 	32	);
insert into user (name, SUS_ID) values	("Marcelo", 	33	);
insert into user (name, SUS_ID) values	("Marcela", 	34	);
insert into user (name, SUS_ID) values	("Morena", 	35	);