-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 12:08:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dengueAnalysisDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dengueAnalysisDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dengueAnalysisDB` DEFAULT CHARACTER SET utf8 ;
USE `dengueAnalysisDB` ;

-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `SUS_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`typeAnalysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`typeAnalysis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`userProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`userProfile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question1` INT(1) NOT NULL,
  `question2` INT(1) NOT NULL,
  `question3` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`healthAgentProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`healthAgentProfile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question1` INT(1) NOT NULL,
  `question2` INT(1) NOT NULL,
  `question3` INT(1) NOT NULL,
  `question4` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`expertProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`expertProfile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question1` INT(1) NOT NULL,
  `question2` INT(1) NOT NULL,
  `question3` INT(1) NOT NULL,
  `question4` INT(1) NOT NULL,
  `question5` INT(1) NOT NULL,
  `question6` INT(1) NOT NULL,
  `question7` INT(1) NOT NULL,
  `question8` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`dengueAnalysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`dengueAnalysis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `age` INT(3) UNSIGNED NOT NULL,
  `weight` DECIMAL(4,1) NOT NULL,
  `height` DECIMAL(2,1) NOT NULL,
  `dateAnalysis` DATETIME NOT NULL,
  `temperature` DECIMAL(3,1) NULL,
  `currentDate` DATE NULL,
  `currentTime` TIME NULL,
  `heartBeat` INT(3) NULL,
  `bloodPressure` VARCHAR(4) NULL,
  `SUS_ID` INT UNSIGNED NOT NULL,
  `symptoms` VARCHAR(255) NULL,
  `expertSuggestion` VARCHAR(255) NULL,
  `dengueProbability` DECIMAL(3,1) NULL,
  `degueHemorrhageProbability` DECIMAL(3,1) NULL,
  `type` INT UNSIGNED NOT NULL,
  `status` INT UNSIGNED NOT NULL,
  `userProfile` INT UNSIGNED NULL,
  `healthAgentProfile` INT UNSIGNED NULL,
  `expertProfile` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dengueAnalysis_typeAnalysis1_idx` (`type` ASC),
  INDEX `fk_dengueAnalysis_status1_idx` (`status` ASC),
  INDEX `fk_dengueAnalysis_userProfile1_idx` (`userProfile` ASC),
  INDEX `fk_dengueAnalysis_healthAgentProfile1_idx` (`healthAgentProfile` ASC),
  INDEX `fk_dengueAnalysis_expertProfile1_idx` (`expertProfile` ASC),
  CONSTRAINT `fk_dengueAnalysis_typeAnalysis1`
    FOREIGN KEY (`type`)
    REFERENCES `dengueAnalysisDB`.`typeAnalysis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dengueAnalysis_status1`
    FOREIGN KEY (`status`)
    REFERENCES `dengueAnalysisDB`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dengueAnalysis_userProfile1`
    FOREIGN KEY (`userProfile`)
    REFERENCES `dengueAnalysisDB`.`userProfile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dengueAnalysis_healthAgentProfile1`
    FOREIGN KEY (`healthAgentProfile`)
    REFERENCES `dengueAnalysisDB`.`healthAgentProfile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dengueAnalysis_expertProfile1`
    FOREIGN KEY (`expertProfile`)
    REFERENCES `dengueAnalysisDB`.`expertProfile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengueAnalysisDB`.`userDengue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengueAnalysisDB`.`userDengue` (
  `SUS_ID` INT UNSIGNED NOT NULL,
  `dengue` INT UNSIGNED NOT NULL,
  INDEX `userDengueSUS_ID_idx` (`SUS_ID` ASC),
  PRIMARY KEY (`SUS_ID`, `dengue`),
  INDEX `userDengueDengue_idx` (`dengue` ASC),
  CONSTRAINT `userDengueSUS_ID`
    FOREIGN KEY (`SUS_ID`)
    REFERENCES `dengueAnalysisDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userDengueDengue`
    FOREIGN KEY (`dengue`)
    REFERENCES `dengueAnalysisDB`.`dengueAnalysis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
